/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVaccinationRouteImport } from './routes/_app/vaccination'
import { Route as AppSymptomsRouteImport } from './routes/_app/symptoms'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppResourcesRouteImport } from './routes/_app/resources'
import { Route as AppPlanningRouteImport } from './routes/_app/planning'
import { Route as AppPassportBuilderRouteImport } from './routes/_app/passport-builder'
import { Route as AppPassportRouteImport } from './routes/_app/passport'
import { Route as AppOfflineRouteImport } from './routes/_app/offline'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppIntelligenceRouteImport } from './routes/_app/intelligence'
import { Route as AppDrSentinelRouteImport } from './routes/_app/dr-sentinel'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as PassportScanIdRouteImport } from './routes/passport.scan.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaccinationRoute = AppVaccinationRouteImport.update({
  id: '/vaccination',
  path: '/vaccination',
  getParentRoute: () => AppRoute,
} as any)
const AppSymptomsRoute = AppSymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningRoute = AppPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppRoute,
} as any)
const AppPassportBuilderRoute = AppPassportBuilderRouteImport.update({
  id: '/passport-builder',
  path: '/passport-builder',
  getParentRoute: () => AppRoute,
} as any)
const AppPassportRoute = AppPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => AppRoute,
} as any)
const AppOfflineRoute = AppOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppDrSentinelRoute = AppDrSentinelRouteImport.update({
  id: '/dr-sentinel',
  path: '/dr-sentinel',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const PassportScanIdRoute = PassportScanIdRouteImport.update({
  id: '/passport/scan/$id',
  path: '/passport/scan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/dr-sentinel': typeof AppDrSentinelRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/map': typeof AppMapRoute
  '/offline': typeof AppOfflineRoute
  '/passport': typeof AppPassportRoute
  '/passport-builder': typeof AppPassportBuilderRoute
  '/planning': typeof AppPlanningRoute
  '/resources': typeof AppResourcesRoute
  '/settings': typeof AppSettingsRoute
  '/symptoms': typeof AppSymptomsRoute
  '/vaccination': typeof AppVaccinationRoute
  '/passport/scan/$id': typeof PassportScanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/dr-sentinel': typeof AppDrSentinelRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/map': typeof AppMapRoute
  '/offline': typeof AppOfflineRoute
  '/passport': typeof AppPassportRoute
  '/passport-builder': typeof AppPassportBuilderRoute
  '/planning': typeof AppPlanningRoute
  '/resources': typeof AppResourcesRoute
  '/settings': typeof AppSettingsRoute
  '/symptoms': typeof AppSymptomsRoute
  '/vaccination': typeof AppVaccinationRoute
  '/passport/scan/$id': typeof PassportScanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/landing': typeof LandingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dr-sentinel': typeof AppDrSentinelRoute
  '/_app/intelligence': typeof AppIntelligenceRoute
  '/_app/map': typeof AppMapRoute
  '/_app/offline': typeof AppOfflineRoute
  '/_app/passport': typeof AppPassportRoute
  '/_app/passport-builder': typeof AppPassportBuilderRoute
  '/_app/planning': typeof AppPlanningRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/symptoms': typeof AppSymptomsRoute
  '/_app/vaccination': typeof AppVaccinationRoute
  '/passport/scan/$id': typeof PassportScanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/sitemap.xml'
    | '/dashboard'
    | '/dr-sentinel'
    | '/intelligence'
    | '/map'
    | '/offline'
    | '/passport'
    | '/passport-builder'
    | '/planning'
    | '/resources'
    | '/settings'
    | '/symptoms'
    | '/vaccination'
    | '/passport/scan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/sitemap.xml'
    | '/dashboard'
    | '/dr-sentinel'
    | '/intelligence'
    | '/map'
    | '/offline'
    | '/passport'
    | '/passport-builder'
    | '/planning'
    | '/resources'
    | '/settings'
    | '/symptoms'
    | '/vaccination'
    | '/passport/scan/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/landing'
    | '/sitemap.xml'
    | '/_app/dashboard'
    | '/_app/dr-sentinel'
    | '/_app/intelligence'
    | '/_app/map'
    | '/_app/offline'
    | '/_app/passport'
    | '/_app/passport-builder'
    | '/_app/planning'
    | '/_app/resources'
    | '/_app/settings'
    | '/_app/symptoms'
    | '/_app/vaccination'
    | '/passport/scan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LandingRoute: typeof LandingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PassportScanIdRoute: typeof PassportScanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vaccination': {
      id: '/_app/vaccination'
      path: '/vaccination'
      fullPath: '/vaccination'
      preLoaderRoute: typeof AppVaccinationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/symptoms': {
      id: '/_app/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof AppSymptomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planning': {
      id: '/_app/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AppPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/passport-builder': {
      id: '/_app/passport-builder'
      path: '/passport-builder'
      fullPath: '/passport-builder'
      preLoaderRoute: typeof AppPassportBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/passport': {
      id: '/_app/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof AppPassportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offline': {
      id: '/_app/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof AppOfflineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intelligence': {
      id: '/_app/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dr-sentinel': {
      id: '/_app/dr-sentinel'
      path: '/dr-sentinel'
      fullPath: '/dr-sentinel'
      preLoaderRoute: typeof AppDrSentinelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/passport/scan/$id': {
      id: '/passport/scan/$id'
      path: '/passport/scan/$id'
      fullPath: '/passport/scan/$id'
      preLoaderRoute: typeof PassportScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDrSentinelRoute: typeof AppDrSentinelRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppMapRoute: typeof AppMapRoute
  AppOfflineRoute: typeof AppOfflineRoute
  AppPassportRoute: typeof AppPassportRoute
  AppPassportBuilderRoute: typeof AppPassportBuilderRoute
  AppPlanningRoute: typeof AppPlanningRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSymptomsRoute: typeof AppSymptomsRoute
  AppVaccinationRoute: typeof AppVaccinationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDrSentinelRoute: AppDrSentinelRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppMapRoute: AppMapRoute,
  AppOfflineRoute: AppOfflineRoute,
  AppPassportRoute: AppPassportRoute,
  AppPassportBuilderRoute: AppPassportBuilderRoute,
  AppPlanningRoute: AppPlanningRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSymptomsRoute: AppSymptomsRoute,
  AppVaccinationRoute: AppVaccinationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LandingRoute: LandingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PassportScanIdRoute: PassportScanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
